joint_limits:
  joint4:
    has_velocity_limits: true
    max_velocity: 1.6
    has_acceleration_limits: false
    max_acceleration: 0
  joint2:
    has_velocity_limits: true
    max_velocity: 1.6
    has_acceleration_limits: false
    max_acceleration: 0
  joint7:
    has_velocity_limits: true
    max_velocity: 1.6
    has_acceleration_limits: false
    max_acceleration: 0
  joint_before_finger1:
    has_velocity_limits: true
    max_velocity: 1.6
    has_acceleration_limits: false
    max_acceleration: 0
  joint6:
    has_velocity_limits: true
    max_velocity: 1.6
    has_acceleration_limits: false
    max_acceleration: 0
  joint5:
    has_velocity_limits: true
    max_velocity: 1.6
    has_acceleration_limits: false
    max_acceleration: 0
  joint1:
    has_velocity_limits: true
    max_velocity: 1.6
    has_acceleration_limits: false
    max_acceleration: 0
  joint3:
    has_velocity_limits: true
    max_velocity: 1.6
    has_acceleration_limits: false
    max_acceleration: 0
  joint_before_finger2:
    has_velocity_limits: true
    max_velocity: 1.6
    has_acceleration_limits: false
    max_acceleration: 0