controller_list:
 - name: arm_controller
   action_ns: follow_joint_trajectory
   type: FollowJointTrajectory
   default: true
   joints:
     - lwr_joint_1
     - lwr_joint_2
     - lwr_joint_3
     - lwr_joint_4
     - lwr_joint_5
     - lwr_joint_6
     - lwr_joint_7
# - name: gripper_controller
   #action_ns: gripper_action
   #type: GripperCommand
   #default: true
   #joints:
     #- joint_before_finger2
     #- joint_before_finger1