controller_list:
  - name: fake_arm_controller
    joints:
      - lwr_joint_1
      - lwr_joint_2
      - lwr_joint_3
      - lwr_joint_4
      - lwr_joint_5
      - lwr_joint_6
      - lwr_joint_7
  - name: fake_gripper_controller
    joints:
      - joint_before_finger1
      - joint_before_finger2
  - name: fake_base_controller
    joints:
      - axis_x
      - axis_y
  - name: fake_arm_base_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: true
    joints:
      - lwr_joint_1
      - lwr_joint_2
      - lwr_joint_3
      - lwr_joint_4
      - lwr_joint_5
      - lwr_joint_6
      - lwr_joint_7
      - axis_x
      - axis_y